config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get '/users', to: 'pages#index', as: :users_all

  get '/dashboard', to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, except: [:index] do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:edit, :update, :destroy]

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end
  # ROUTE TO THE USER'S PROFILE
  get ':username', to: 'profiles#show', as: :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
 class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  #FOLLOWING SYSTEM

  #the ones who are following the user (THEY FOLLOW ME)
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  #the ones to whom the user follows (I FOLLOW)
  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

    def after_sign_in_path_for(resource)
      "/dashboard"
    end

    def after_sign_up_path_for(resource)
      "/:username"
    end

    def after_update_path_for(resource)
      profile_path(resource.username)
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :username, :photo, :email, :password, :about)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:full_name, :username, :photo, :email, :about, :password, :current_password)}
    end

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user

    authorize @comment

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    authorize @comment

    redirect_to post_path(@comment.post)
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home; end

  def index
    @users = User.all
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = policy_scope(Post).order(created_at: :desc)
    @users = User.where.not(id: current_user.id)
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
    @markers = [
      {
        lat: @post.latitude,
        lng: @post.longitude,
      }
    ]
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize @post
    if @post.save
      respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'The post was succesfully created! :)' }
      format.js {}
      end
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'Your post was succesfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_path, notice: 'Your post was destroyed!'
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:description, :photo, :location)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path(@user.username)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
    skip_authorization
  end

  def user_params
    params.require(:user).permit(:photo, :username, :full_name, :about, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow]

  def index
    @users = User.where.not(id: current_user.id)
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
    skip_authorization
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render action: :follow }
      end
    end
    skip_authorization
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comments mt-2">
  <% if !@comments.blank? %>
    <% @comments.reverse.each do |comment| %>
    <div class="comment-card bg-white mb-2 d-flex align-items-center">
      <strong><p class="mb-0 mr-2"><%= comment.user.username %></p></strong>
      <p class="mb-0 comment-content"><%= comment.content %></p>
      <% if  policy(comment).update?%>
        <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_comment_path(comment) %>
      <% end %>
      <% if policy(comment).destroy? %>
        <%= link_to '<small><i class="fas fa-trash-alt ml-2"></i></small>'.html_safe, comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-4 bg-white py-4 px-4 mt-5">
      <h1>Edit</h1>
      <%= simple_form_for (@comment) do |f|%>
        <%= f.input :content %>
        <%= f.submit class: 'btn btn-primary w-100' %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramCopycat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="introduction">
  <h1>
    <span id="greeting-typed-text"></span>
  </h1>
  <div class="intro d-flex font-weight-normal">
    <%= image_tag "profile.jpg", class: 'avatar-large center-block avatar-home' %>
    <p>Thank you so much for passing by! I am Guillem Delás, a Junio Full-Stack Web Developer based in Barcelona.</p>
    <div class="links">
      <div class="github d-flex align-items-center">
        <%= link_to '<i class="fab fa-github"></i>'.html_safe, 'https://github.com/guillemdlopez', class: 'ml-2', id: 'social-link', target: :_blank, style: 'font-size: 24px;'  %>
      </div>
      <div class="twitter"></div>
      <div class="linkedin d-flex align-items-center">

        <%= link_to '<i class="fab fa-linkedin"></i>'.html_safe, 'https://www.linkedin.com/in/guillemdelas/', class: 'ml-2', id: 'social-link', target: :_blank, style: 'font-size: 24px;'  %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="row justify-content-center pb-5">
    <div class="col-lg-6">
      <h2 class="text-center mt-5 mb-3">Look for friends!</h2>
      <% @users.reject { |user| user == current_user }.each do |user| %>
        <div class="user-card mb-4 bg-white px-2 py-2 d-flex align-items-center shadow">
          <%= link_to profile_path(user.username)  do %>
            <%= cl_image_tag user.photo.key, class: 'avatar' %>
            <div class="user-card-info ml-3 flex-grow-1">
              <p class="mb-0 font-weight-bold"><%= user.username %></p>
              <p class="mb-0"><%= user.full_name %></p>
              <p class="mb-0 text-secondary"><%= truncate(user.about, length: 50) %></p>
          <% end %>
            </div>
          <% if current_user.is_following?(user.id) %>
             <p class="mb-0 ml-2" id="following-sign">FOLLOWING</p>
          <% else %>
            <%= link_to "Follow", follow_user_path(user.id), method: :post, remote: true , class: 'font-weight-bold text-primary ml-3 follow-link' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-6 bg-white px-4 py-4 rounded">
      <%= simple_form_for(@post) do |f| %>
        <%= f.input :description, placeholder: 'Say something inspiring' %>
        <%= f.input :location, placeholder: 'Parc Güell, Barcelona' %>
        <%= f.file_field :photo, as: :file %>
        <%= f.submit class: 'btn btn-primary w-100 mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="wrapper dashboard pb-5">
  <div class="container">
    <div class="row justify-content-center pb-5">
      <div class="col-lg-8 avatar-menu">
        <!-- EACH POST -->
        <% @posts.each do |post| %>
            <div class="post-card border bg-white mt-4 rounded">
              <!-- USERNAME, LOCATION, FOLLOWING SIGN -->
              <div class="info-post py-2 px-3">
                <% if post.user.photo.attached? %>
                  <%= cl_image_tag post.user.photo.key, class: 'avatar' %>
                <% end %>
                <div class="user-info ml-3">
                  <div class="username-following d-flex align-items-center">
                    <%= link_to profile_path(post.user.username) do %> <!--- LINK TO PROFILE --->
                      <strong><p class="mb-0 text-dark user ml-0" id="username-post"><%= post.user.username %></p></strong>
                    <% end %>
                    <% if current_user.is_following?(post.user) %>
                      <p class="mb-0 ml-2" id="following-sign">FOLLOWING</p>
                    <% end %>
                  </div>
                    <p class="mb-0 small text-secondary"><%= post.location %></p>
                </div>
                <strong><p class="mb-0">···</p></strong>
              </div>
              <div class="image-post text-center">
                <%= link_to post_path(post.id) do %>
                <% if post.photo.attached? %>
                  <%= cl_image_tag post.photo.key, gravity: 'center', class: 'img-post'  %>
                <% end %>
              </div>
              <div class="post-card-icons py-2 px-3">
                <div class="icons mt-4">
                  <div class="icons-left">
                    <i class="far fa-heart"></i>
                    <i class="far fa-comment"></i>
                    <i class="far fa-paper-plane"></i>
                  </div>
                  <div class="icon-right">
                    <i class="far fa-bookmark"></i>
                  </div>
                </div>
              </div>
              <div class="post-card-comments ml-3 mr-3 mb-4">
                <p class="mb-0 font-weight-bolder small text-dark mt-2">54 Me gusta</p>
                <div class="post-card-description d-flex mt-1 mb-3">
                  <p class="mr-2 mb-0"> <strong><%= post.user.username %></strong></p>
                  <p class="mr-2 mb-0"><%= post.description %></p>
                </div>
                <% if !post.comments.empty? && post.comments.count > 2 %>
                  <%= link_to 'See more comments', post_path(post.id), class: 'link-more-comments' %>
                <% end %>
                <% post.comments.last(2).reverse.each do |comment| %>
                  <div class="user-comment d-flex align-items-center mt-2 mb-0">
                    <strong><p class="mb-0 mr-2"><%= comment.user.username %></p></strong>
                    <p class="mb-0 comment-content"><%= comment.content %></p>
                    <small><i class="far fa-heart"></i></small>
                  </div>
                <% end %>
                <p class="mt-3" id="publication-date"><small><%=post.created_at.strftime("%a %d of %B, %H:%M:%S")%></small></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <!-- END OF EACH POST -->
      <!--- SIDE MENU --->
      <div class="col-lg-4 pb-5">
        <div class="side-menu">
          <%= link_to profile_path(current_user.username) do %>
            <div class="user-info d-flex align-items-center">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: 'avatar' %>
              <% end %>
              <div class="username ml-2">
                <strong><p class="mb-0"><%= current_user.username %></p></strong>
                <p class="mb-0 small text-secondary"><%= current_user.full_name %></p>
              </div>
            </div>
          <% end %>
          <!-- USERS I AM FOLLOWING -->
          <div class="followers mt-4 d-flex justify-content-between">
            <p class="mb-1 text-secondary font-weight-bold">Users you follow (<%= current_user.following.count %>)</p>
          </div>
          <div class="following mb-4">
            <% current_user.following.sample(4).each do |followee| %>
              <%= link_to profile_path(followee.username) do %>
                <div class="followee d-flex align-items-center mb-2">
                  <%= cl_image_tag followee.photo.key, class: 'avatar' %>
                  <p class="mb-0 ml-2"><strong><%= followee.username %></p></strong>
                </div>
              <% end %>
            <% end %>
          </div>
          <!-- ALL THE OTHER USERS -->
          <div class="other-users d-flex justify-content-between">
            <p class="mb-0 text-secondary font-weight-bold">Other users</p>
            <%= link_to 'See all', users_path, class: 'small font-weight-bolder text-dark' %>
          </div>
          <%= render @users.sample(4)%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row justify-content-center">
  <div class="col-lg-4 bg-white py-4 mt-5 rounded px-4">
    <h1>Create a new post</h1>

    <%= simple_form_for(@post) do |f| %>
      <%= f.input :description, placeholder: 'Say something inspiring' %>
      <%= f.input :location, placeholder: 'Parc Güell, Barcelona' %>
      <%= f.input :photo, as: :file, label: false %>

        <%= f.submit class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-4 mb-5">
    <!---MAP--->
    <% unless @post.latitude == nil && @post.longitude == nil%>
      <div
        id="map"
        class="mb-2"
        style="width: 100%;
        height: 200px;
        margin-left: 15px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <% end %>
    <div class="col-lg-8">
      <%= cl_image_tag @post.photo.key, class: 'img-post' %>
    </div>
    <!-- POST -->
    <div class="col-lg-4 bg-white py-4 px-4">
      <%= link_to profile_path(@post.user.username) do%>
        <div class="user-info d-flex align-items-start border-bottom">
          <%= cl_image_tag @post.user.photo.key, class: 'avatar' %>
          <div class="username-location ml-2 mr-2">
            <p class="mb-0"><strong><%= @post.user.username %></strong></p>
            <% end %>
            <p class="mb-0 text-secondary"><small><%= @post.location %></small></p>
            <p class="pt-2"><%= @post.description %></p>
          </div>
          <% if current_user.is_following?(@post.user.id) %>
            <p class="mb-0 ml-2" id="following-sign">FOLLOWING</p>
          <% end %>
        </div>
      <!-- ICONS -->
      <div class="icons-show-post">
        <%= link_to '<i class="fas fa-home"></i>'.html_safe, dashboard_path %>
        <% if policy(@post).update?%>
          <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_post_path(@post) %>
        <% end %>
        <% if policy(@post).destroy? %>
          <small><i class="fas fa-trash-alt" id="btn-delete"></i></small>
          <%= link_to "", @post, method: :delete, id: 'delete-link', class: 'hidden' %>
        <% end %>
      </div>

      <div class="comments mt-2 mb-4">
        <p class="mt-3" id="publication-date"><small><%=@post.created_at.strftime("%a %d of %B, %H:%M:%S")%></small></p>
        <% if !@comments.blank? %>
          <% @comments.reverse.each do |comment| %>
          <div class="comment-card bg-white mb-2 d-flex align-items-center">
            <strong><p class="mb-0 mr-2"><%= comment.user.username %></p></strong>
            <p class="mb-0 comment-content"><%= comment.content %></p>
            <% if  policy(comment).update?%>
              <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_comment_path(comment) %>
            <% end %>
            <% if policy(comment).destroy? %>
              <small><i class="fas fa-trash-alt ml-2" id="btn-delete-comment"></i></small>
              <%= link_to "", comment_path(comment), method: :delete, id: "link", class: "hidden" %>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
      <div class="post-card-comment-form">
        <div class="icons d-flex align-items-center justify-content-between mb-2">
          <div class="all-unless-bookmark">
            <i class="far fa-heart"></i>
            <i class="far fa-comment"></i>
            <i class="far fa-paper-plane"></i>
          </div>
          <i class="far fa-bookmark"></i>
        </div>
        <% if current_user != @post.user && @post.comments.count == 0 %>
          <p class="mb-0 text-center"><strong>Be the first one to comment!</strong></p>
        <% end %>
        <%= simple_form_for([@post, @comment], remote: true) do |f| %>
          <%= f.input :content, placeholder: 'Add a comment...', label: false %>
          <%= f.submit class: 'btn btn-primary w-100' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="user-banner d-flex justify-content-center align-items-center mb-5 mt-5">
  <%= cl_image_tag @user.photo.key, class: 'avatar-large' %>
    <div class="user-banner-info">
      <div class="username-btn d-flex align-items-center mb-2">
        <h3 class="font-weight-normal mb-0"><%=@user.username%></h3>
        <% if current_user == @user %>
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn-edit ml-3' %>
        <% end %>
        <% if current_user.is_following?(@user) %>
          <p class="mb-0 ml-2" id="following-sign">FOLLOWING</p>
        <% end %>
      </div>
      <div class="d-flex justify-content-evently" id="user-info-profile">
        <h6 class="mb-0 mr-3 text-dark"><strong><%= posts = @user.posts.count %></strong> <%= posts == 0 || posts > 1 ? 'posts' : 'post' %></h6>
        <h6 class="mb-0 mr-3 text-dark"><strong><%= followers = @user.followers.count %></strong> <%= followers == 0 || followers > 1 ? 'followers' : 'follower' %></h6>
        <h6 class="mb-0 mr-3 text-dark"><strong><%= @user.following.count %></strong> following</h6>
      </div>
      <p class="mb-0 mt-2 text-dark"><%= @user.full_name %></p>
      <p class="mb-0"> <%= @user.about %> </p>
    </div>
  </div>
  <!-- USER POSTS --->
  <% if  current_user == @user && @user.posts.count == 0%>
    <div class="text-center border-top pt-5">
      <p class="mb-0">You don't have any posts! (yet😏)</p>
    </div>
    <%= link_to new_post_path do %>
      <h6 class="btn-new-post-profile text-center text-primary font-weight-bold mt-2">👉 Create a post 👈</h6>
    <% end %>
  <% else %>
    <div class="cards border-top pt-5 mb-5">
      <% @posts.each do |post| %>
      <%= link_to post_path(post) do %>
        <div class="card" style="background-image: linear-gradient(rgba(2,0,22,0.4) 0%, rgba(0,0,0,0.1) 100%), url('<%= cl_image_path post.photo.key %>')">
          <div class="post-info d-flex text-light justify-content-center align-items-center">
            <h5 class="mr-5 mb-0"><i class="fas fa-heart"></i> 54</h5>
            <h5 class="mb-0"><i class="fas fa-comment"></i> <%= post.comments.count %></h5>
          </div>
        </div>
      <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to 'Instacram', dashboard_path, class: 'logo-navbar' %>
    <div class="form">
      <% if user_signed_in? %>
        <%= form_tag users_path, method: :get, class:'d-flex justify-content-center align-items-center' do %>
          <%= text_field_tag :query, params[:query], class: "form-input text-center", placeholder: "Look for friends" %>
            <button type="submit" class="btn btn-primary ml-2 rounded">
              <i class="fas fa-search"></i>
            </button>
        <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto align-items-center">
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'New post', new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, gravity: 'face', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/cveneziani", gravity: 'face', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path(current_user.username), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item d-flex">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <strong><%= link_to "Sign up", new_user_registration_path, class: "nav-link text-primary" %></strong>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div data-user=<%= user.id %>>
    <div class="users-follow-unfollow d-flex mb-2 align-items-center">
        <%= cl_image_tag user.photo.key, class: 'avatar' %>
        <div class="user-card flex-grow-1 ml-2">
          <p class="mb-0 users-to-follow-username flex-grow-1"><strong><%= user.username %></p></strong>
          <p class="mb-0 small text-dark text-secondary"><%= user.about %></p>
        </div>
      <% if current_user.is_following?(user.id) %>
        <%= link_to "Unfollow", unfollow_user_path(user.id), method: :post, remote: true, class: 'font-weight-bold ml-2 unfollow-link' %>
      <% else %>
        <%= link_to "Follow", follow_user_path(user.id), method: :post, remote: true , class: 'font-weight-bold text-primary ml-2 follow-link' %>
      <% end %>
    </div>
</div>

app/views/users/follows.js.erb
function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.outerHTML = userHTML;
}

renderUser('<%= j render @user %>');